### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by aramaziakin** [NieR-Rein-Guide/nier-rein-apps#1]
I can't compile nier-rein-gui because it tries to get a project called ImGui.Forms.csproj but I can't find this anywhere.

**Comment by aramaziakin** [comment]
I manged to fix it based on some edits a fork had done, basically removing reference to the file I mentioned above and adding in some lines referencing the package version of ImGui.

**Comment by Priestru** [comment]
Can you explain what lines you added?

**Comment by aramaziakin** [comment]
> Can you explain what lines you added?

Sorry, I actually ended up just using one of the forks in the end, I think it was an older version that didn't rely on the missing file. Looking at them now though it seems like the forks have updated and now both need the file as well.
I'll see if I can upload the version I have when I'm at my PC, unless someone can tell us how to get the file we need.

**Comment by Priestru** [comment]
Yeah found older version. Well i'm somewhat interested in what was developed later.

**Comment by onepiecefreak3** [comment]
Should be fixed in the newest commits.
