### ISSUE TITLE
Where am I looking for updates now?

### ISSUE THREAD

**Issue by myndxero** [NieR-Rein-Guide/nier-rein-apps#18]
Still working off the last release onepiece did. I see files updating regularly but no releases. Do I need to figure out how to compile myself? I began looking into that, just haven't followed through, my computer has been down a majority of the time. Sometimes it stays on long enough to load up haha.

Thanks!

**Comment by BillyCool** [comment]
Hey there, I'm not using the app personally so won't be maintaining it or publishing new versions for it going forward. If it's something you use and want to contribute, you're welcomed to though :)

**Comment by myndxero** [comment]
Is there an alternative? I see files being updated. Just a small handful of
things I hate doing manually, like anything to do w the map! Birds, lost
treasures.

I'm outdated on coding. Or I would consider.

You quit the game too? Seems a lot of people are sadly.

**Comment by BillyCool** [comment]
Don't believe there's anything else like it. I haven't quit, just don't use that app myself, it's something OPF worked on initially but he's not playing anymore. I mostly focus on maintaining the tools we use for the NRG website and for datamines.

**Comment by myndxero** [comment]
He said it should handle new content and so far it has. I guess until there's new mechanics it should be solid, though like I mentioned, I really only use it to handle the map features. I do not care for running between birds and treasures. Too worried about a ban to use the subjugation thing, even to reset my score to what I finished the previous season.

I miss harassing him on Discord for issues due to my errors but initially thinking it was the app haha. He tried on my behalf to fix my cash shop ban which I really appreciated. In the end I guess applibot did me a favor.

I find myself playing less, not always keeping up with dailies and such, and I hadn't really slowed down since launch. I'm so mad about them cutting english audio.

Anyway. Thanks for response and time. I'll go ahead and close this.
